[package]
name = "vss"
version = "0.1.0"
edition = "2024"

[dependencies]
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"
num-integer = "0.1"
rand = { version = "0.8", features = ["std"] }
clap = { version = "4", features = ["derive"] } 
